version: '2.2'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    init: true
    network_mode: bridge
    expose:
      - '80'
    environment:
      VIRTUAL_HOST:
      LETSENCRYPT_HOST:
      LETSENCRYPT_EMAIL:
    volumes:
      - ./server:/var/www/html
      - ./db:/run/db
